version: "3.8"
services:
  backend:
    image: ton-dockerhub/projet-backend:latest
    container_name: api_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - credencia-network

  # Le frontend (Vue.js) n'est pas ici car il est déployé sur S3/CloudFront.
  # La BDD n'est pas ici car elle est gérée par AWS RDS.

networks:
  credencia-network:
    driver: bridge