export const mockProjects = [
  {
    id: 1,
    title: "Plateforme E-Learning",
    description:
      "Système complet de gestion de cours en ligne avec suivi de progression, gestion des utilisateurs, tableau de bord enseignant et validation académique.",
    type: "Intégration",
    validationStatus: "APPROVED",
    technologies: ["Vue 3", "Express", "PostgreSQL", "Docker", "JWT"],
    createdAt: "2026-03-12",
    role: "Chef de projet & Dev Fullstack",
    teamSize: "4 membres",
    validatorName: "Pr. Moussaoui",
    validationComment:
      "Excellent travail, architecture propre et documentation claire.",
    githubUrl: "https://github.com/example/e-learning",
    demoUrl: "https://demo.example.com",
    documentationUrl: "https://docs.example.com",
    portfolioUrl: "https://portfolio.example.com",
    attachments: [
      { id: 1, name: "Rapport du projet.pdf", type: "PDF", url: "#" },
      {
        id: 2,
        name: "Certificat de participation.png",
        type: "IMAGE",
        url: "#",
      },
    ],
    validationHistory: [
      {
        id: 1,
        status: "DRAFT",
        title: "Projet créé",
        comment: "Le projet a été enregistré comme brouillon.",
        actorName: "Mohamed Zaaboul",
        actorRole: "Étudiant",
        createdAt: "2026-03-12",
      },
      {
        id: 2,
        status: "PENDING",
        title: "Projet soumis",
        comment: "Projet envoyé pour validation académique.",
        actorName: "Mohamed Zaaboul",
        actorRole: "Étudiant",
        createdAt: "2026-03-14",
      },
      {
        id: 3,
        status: "APPROVED",
        title: "Projet validé",
        comment:
          "Excellent travail, architecture propre et documentation claire.",
        actorName: "Pr. Moussaoui",
        actorRole: "Validateur académique",
        createdAt: "2026-03-18",
      },
    ],
    screenshots: [
      { id: 1, title: "Dashboard", imageUrl: null },
      { id: 2, title: "Cours", imageUrl: null },
      { id: 3, title: "Profil", imageUrl: null },
    ],
  },

  {
    id: 2,
    title: "Pipeline CI/CD DevSecOps",
    description:
      "Pipeline automatisé pour tester, analyser, construire et déployer une application web avec une approche DevSecOps.",
    type: "Module",
    validationStatus: "PENDING",
    technologies: ["GitHub Actions", "Docker", "Trivy", "Node.js"],
    createdAt: "2026-04-08",
    role: "DevOps",
    teamSize: "3 membres",
    validatorName: "Pr. El Amrani",
    validationComment: null,
    githubUrl: "https://github.com/example/devsecops-pipeline",
    demoUrl: null,
    documentationUrl: "https://docs.example.com/devsecops",
    portfolioUrl: null,
    attachments: [
      { id: 1, name: "Architecture pipeline.pdf", type: "PDF", url: "#" },
    ],
    validationHistory: [
      {
        id: 1,
        status: "DRAFT",
        title: "Projet créé",
        comment: "Le projet a été préparé avec les premières étapes CI.",
        actorName: "Mohamed Zaaboul",
        actorRole: "Étudiant",
        createdAt: "2026-04-08",
      },
      {
        id: 2,
        status: "PENDING",
        title: "Projet soumis",
        comment: "Pipeline soumis pour validation du module DevSecOps.",
        actorName: "Mohamed Zaaboul",
        actorRole: "Étudiant",
        createdAt: "2026-04-10",
      },
    ],
    screenshots: [
      { id: 1, title: "Workflow CI", imageUrl: null },
      { id: 2, title: "Rapport Trivy", imageUrl: null },
    ],
  },

  {
    id: 3,
    title: "Dashboard Analytics",
    description:
      "Tableau de bord interactif permettant de visualiser les données académiques avec des graphiques dynamiques et des filtres par période.",
    type: "Personnel",
    validationStatus: "DRAFT",
    technologies: ["Vue 3", "Chart.js", "Pinia"],
    createdAt: "2026-05-01",
    role: "Développeur Frontend",
    teamSize: "Projet individuel",
    validatorName: null,
    validationComment: null,
    githubUrl: "https://github.com/example/dashboard-analytics",
    demoUrl: null,
    documentationUrl: null,
    portfolioUrl: null,
    attachments: [],
    validationHistory: [
      {
        id: 1,
        status: "DRAFT",
        title: "Brouillon créé",
        comment: "Projet enregistré mais pas encore soumis.",
        actorName: "Mohamed Zaaboul",
        actorRole: "Étudiant",
        createdAt: "2026-05-01",
      },
    ],
    screenshots: [
      { id: 1, title: "Vue globale", imageUrl: null },
      { id: 2, title: "Graphiques", imageUrl: null },
    ],
  },

  {
    id: 4,
    title: "Hackathon Green Campus",
    description:
      "Prototype d’une plateforme de suivi énergétique intelligente pour aider les établissements universitaires à mieux analyser leur consommation.",
    type: "Hackathon",
    validationStatus: "CHANGES_REQUESTED",
    technologies: ["Vue 3", "Firebase", "Chart.js"],
    createdAt: "2026-02-19",
    role: "Frontend & Présentation",
    teamSize: "5 membres",
    validatorName: "Pr. Benali",
    validationComment:
      "Ajouter plus de détails sur la collecte des données et les résultats obtenus.",
    githubUrl: "https://github.com/example/green-campus",
    demoUrl: "https://green-campus.example.com",
    documentationUrl: null,
    portfolioUrl: null,
    attachments: [
      { id: 1, name: "Présentation hackathon.pdf", type: "PDF", url: "#" },
      { id: 2, name: "Attestation hackathon.png", type: "IMAGE", url: "#" },
    ],
    validationHistory: [
      {
        id: 1,
        status: "DRAFT",
        title: "Projet créé",
        comment: "Prototype hackathon ajouté au portfolio.",
        actorName: "Mohamed Zaaboul",
        actorRole: "Étudiant",
        createdAt: "2026-02-19",
      },
      {
        id: 2,
        status: "PENDING",
        title: "Projet soumis",
        comment: "Projet envoyé au validateur pour évaluation.",
        actorName: "Mohamed Zaaboul",
        actorRole: "Étudiant",
        createdAt: "2026-02-21",
      },
      {
        id: 3,
        status: "CHANGES_REQUESTED",
        title: "Corrections demandées",
        comment: "Ajouter les sources des données et préciser les résultats.",
        actorName: "Pr. Benali",
        actorRole: "Validateur académique",
        createdAt: "2026-02-24",
      },
    ],
    screenshots: [
      { id: 1, title: "Accueil", imageUrl: null },
      { id: 2, title: "Consommation", imageUrl: null },
      { id: 3, title: "Recommandations", imageUrl: null },
    ],
  },

  {
    id: 5,
    title: "API REST Sécurisée",
    description:
      "Backend REST avec authentification JWT, rôles utilisateurs, middleware de sécurité, tests automatisés et documentation Swagger.",
    type: "Module",
    validationStatus: "REJECTED",
    technologies: ["Express", "JWT", "Swagger", "Jest"],
    createdAt: "2026-01-27",
    role: "Backend Developer",
    teamSize: "2 membres",
    validatorName: "Mme Ghizlan",
    validationComment:
      "Le projet manque encore de tests de sécurité et de validation complète.",
    githubUrl: "https://github.com/example/secure-api",
    demoUrl: null,
    documentationUrl: "https://docs.example.com/secure-api",
    portfolioUrl: null,
    attachments: [
      { id: 1, name: "Documentation Swagger.pdf", type: "PDF", url: "#" },
    ],
    validationHistory: [
      {
        id: 1,
        status: "DRAFT",
        title: "Projet créé",
        comment: "API ajoutée avec la première version de la documentation.",
        actorName: "Mohamed Zaaboul",
        actorRole: "Étudiant",
        createdAt: "2026-01-27",
      },
      {
        id: 2,
        status: "PENDING",
        title: "Projet soumis",
        comment: "Projet soumis pour validation du module backend.",
        actorName: "Mohamed Zaaboul",
        actorRole: "Étudiant",
        createdAt: "2026-01-29",
      },
      {
        id: 3,
        status: "REJECTED",
        title: "Projet refusé",
        comment: "Tests de sécurité insuffisants pour valider le projet.",
        actorName: "Mme Ghizlan",
        actorRole: "Validatrice académique",
        createdAt: "2026-02-02",
      },
    ],
    screenshots: [
      { id: 1, title: "Swagger", imageUrl: null },
      { id: 2, title: "Tests Jest", imageUrl: null },
    ],
  },

  {
    id: 6,
    title: "Stage Fullstack Web",
    description:
      "Développement d’une application interne de gestion documentaire durant un stage en entreprise, avec gestion des rôles et interface responsive.",
    type: "Stage",
    validationStatus: "APPROVED",
    technologies: ["React", "Node.js", "MongoDB"],
    createdAt: "2025-12-11",
    role: "Stagiaire Fullstack",
    teamSize: "Équipe entreprise",
    validatorName: "Pr. Haddad",
    validationComment:
      "Stage validé avec un bon niveau technique et une intégration professionnelle réussie.",
    githubUrl: null,
    demoUrl: null,
    documentationUrl: null,
    portfolioUrl: "https://portfolio.example.com/stage-fullstack",
    attachments: [
      { id: 1, name: "Rapport de stage.pdf", type: "PDF", url: "#" },
      { id: 2, name: "Attestation de stage.pdf", type: "PDF", url: "#" },
    ],
    validationHistory: [
      {
        id: 1,
        status: "DRAFT",
        title: "Stage ajouté",
        comment: "Expérience de stage ajoutée au portfolio.",
        actorName: "Mohamed Zaaboul",
        actorRole: "Étudiant",
        createdAt: "2025-12-11",
      },
      {
        id: 2,
        status: "APPROVED",
        title: "Stage validé",
        comment: "Stage validé avec un bon retour académique.",
        actorName: "Pr. Haddad",
        actorRole: "Validateur académique",
        createdAt: "2025-12-18",
      },
    ],
    screenshots: [
      { id: 1, title: "Interface interne", imageUrl: null },
      { id: 2, title: "Gestion documents", imageUrl: null },
    ],
  },
];
