-- This migration previously duplicated the schema already created by earlier
-- migrations, which made clean databases fail with "type already exists"
-- errors. It is intentionally left as a no-op so the rest of the migration
-- chain can be applied normally.
