export const DASHBOARD_ICONS = Object.freeze({
  activities: "assignment",
  adminVerified: "verified",
  badges: "workspace_premium",
  emailVerified: "mark_email_read",
  internships: "work",
  pendingRequests: "schedule",
  professional: "business_center",
  professors: "person",
  profileCompletion: "account_circle",
  projects: "folder",
  recommendations: "forum",
  reviews: "fact_check",
  score: "military_tech",
  students: "school",
  suspendedAccount: "block",
  supervisedInternships: "supervisor_account",
  users: "groups",
  validatedAchievements: "verified",
});
